apiVersion: apps/v1
kind: Deployment
metadata:
  name: markdownlang-telemetryd
  annotations:
    operator.1password.io/auto-restart: "true"
    keel.sh/policy: all
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@hourly"
  labels:
    app.kubernetes.io/name: markdownlang-telemetryd
    app.kubernetes.io/part-of: markdownlang
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: markdownlang-telemetryd
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: markdownlang-telemetryd
        app.kubernetes.io/part-of: markdownlang
    spec:
      containers:
        - name: markdownlang-telemetryd
          image: reg.xeiaso.net/xe/x/markdownlang-telemetryd:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 9100
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          securityContext:
            runAsUser: 65532
            runAsGroup: 65532
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
            readOnlyRootFilesystem: true
          env:
            - name: MARKDOWNLANG_TELEMETRY_BUCKET
              value: "xe-markdownlang-telemetry"
            - name: MARKDOWNLANG_TELEMETRY_DISCORD_WEBHOOK
              valueFrom:
                secretKeyRef:
                  name: markdownlang-telemetryd
                  key: discord-webhook
            - name: MARKDOWNLANG_TELEMETRY_XE_WEBHOOK
              valueFrom:
                secretKeyRef:
                  name: markdownlang-telemetryd
                  key: xe-webhook
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: markdownlang-telemetryd
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: markdownlang-telemetryd
                  key: aws-secret-access-key
            - name: AWS_REGION
              value: "auto"
            - name: AWS_ENDPOINT_URL
              value: "https://t3.storage.dev"
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
